package com.dyneinfo.zazh.model;

import java.io.Serializable;

import java.util.HashSet;
import java.util.Set;



import net.java.dev.common.tree.LongTreeNode;



/**
 * Menu generated by lisc.
 *
 * @author lisc
 * @since 2009年12月01日 下午 20时18分45秒0
 */

public class Menu extends LongTreeNode<Menu> {
    /** * serial. */
    static final long serialVersionUID = 0L;

    /** * id. */
    private Long id;   //ID 

    /** * parent. */
    private Menu parent;

    /** * name. */
    private String name;  //节点显示

    /** * theSort. */
    private Integer theSort;//排序

    /** * qtip. */
    private String qtip; //提示

    /** * iconCls. */
    private String iconCls;  //图标 

    /** * forward. */
    private String url; // 链接 

    /** * descn. */
    private String descn; //描述信息 
    
    private String hrefTarget;    //链接指向 

    private boolean expandable;   //是否展开 


    /** * menus. */
    private Set<Menu> children = new HashSet<Menu>(0);



    /** * checked. */
    private boolean checked = false;

    /** * 构造方法. */
    public Menu() {
    }

    /** * @return id. */

    public Long getId() {
        return id;
    }

    /** * @param id id. */
    public void setId(Long id) {
        this.id = id;
    }

    /** * @return parent. */
    public Menu getParent() {
        return parent;
    }

    /** * @param parent Menu. */
    public void setParent(Menu parent) {
        this.parent = parent;
    }

    /** * @return name. */
  
    public String getName() {
        return name;
    }

    /** * @param name name. */
    public void setName(String name) {
        this.name = name;
    }

    /** * @return theSort. */
  
    public Integer getTheSort() {
        return theSort;
    }

    /** * @param theSort Integer. */
    public void setTheSort(Integer theSort) {
        this.theSort = theSort;
    }

    /** * @return qtip. */
   
    public String getQtip() {
        return qtip;
    }

    /** * @param qtip String. */
    public void setQtip(String qtip) {
        this.qtip = qtip;
    }

    /** * @return iconCls. */
   
    public String getIconCls() {
        return iconCls;
    }

    /** * @param iconCls icon. */
    public void setIconCls(String iconCls) {
        this.iconCls = iconCls;
    }

    /** * @return url. */
    
    public String getUrl() {
        return url;
    }

    /** * @param url String. */
    public void setUrl(String url) {
        this.url = url;
    }

    /** * @return descn. */
   
    public String getDescn() {
        return descn;
    }

    /** * @param descn descn. */
    public void setDescn(String descn) {
        this.descn = descn;
    }

    /** * @return children. */

    public Set<Menu> getChildren() {
        return children;
    }

    /** * @param children Set. */
    public void setChildren(Set<Menu> children) {
        this.children = children;
    }


    /** * @return isChecked. */
 
    public boolean isChecked() {
        return checked;
    }

    /** * @param checked boolean. */
    public void setChecked(boolean checked) {
        this.checked = checked;
    }

	public String getHrefTarget() {
		return hrefTarget;
	}

	public void setHrefTarget(String hrefTarget) {
		this.hrefTarget = hrefTarget;
	}

	public boolean isExpandable() {
		return expandable;
	}

	public void setExpandable(boolean expandable) {
		this.expandable = expandable;
	}
}
